include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "racket/base.yml"

variables:
  RACO_PKG_NAME: jm-toolbox

semantic-releaser:
  variables:
    RELEASE_ASSETS: '[{ "path": "./main", "label": "the executable" }]'
