image: racket/racket:8.3-full

stages:
  - test
  - build

before_script:
  - raco setup --fail-fast

coverage:
  stage: test
  script:
    - raco pkg install --batch --auto cover
    - raco cover .

test:
  stage: test
  script:
    - raco test *.rkt

build:
  stage: build
  script:
    - raco exe main.rkt
