image: racket/racket:8.3-full

variables:
  RACO_PKG_NAME: jm-toolbox

stages:
  - test
  - build
  - publish

before_script:
  - raco pkg install --no-docs --batch --auto --name $RACO_PKG_NAME
  - raco setup --fail-fast

coverage:
  stage: test
  script:
    - raco pkg install --batch --auto cover
    - raco cover .
  artifacts:
    paths:
      - coverage

test:
  stage: test
  script:
    - raco setup --check-pkg-deps --unused-pkg-deps $RACO_PKG_NAME
    - raco test -x -p $RACO_PKG_NAME

build:
  stage: build
  script:
    - raco exe main.rkt

semantic-releaser:
  image: jackzzz92/semantic-release-gitlab:latest
  variables:
    DEBUG_RELEASE: 1
    USE_DEFAULT_CONFIG: 1
    CI_BRANCH_NAME: $CI_COMMIT_REF_NAME
  stage: publish
  only:
    - branches
  needs:
    - build
  dependencies:
    - build
  before_script: []
  script:
    - /home/releaser/init.sh
