image: racket/racket:8.3-full

stages:
  - test
  - build
  - publish

before_script:
  - raco setup --fail-fast
  - raco pkg install --batch --auto

coverage:
  stage: test
  script:
    - raco pkg install --batch --auto cover
    - raco cover .

test:
  stage: test
  script:
    - raco test *.rkt

build:
  stage: build
  script:
    - raco exe main.rkt

semantic-releaser:
  image: jackzzz92/semantic-release-gitlab
  variables:
    USE_DEFAULT_CONFIG: 1
    CI_BRANCH_NAME: $CI_COMMIT_REF_NAME
  stage: publish
  only:
    - branches
  needs:
    - build
  dependencies:
    - build
  before_script: []
  script:
    - /home/releaser/init.sh
