image: racket/racket:8.3-full

stages:
  - test
  - build

before_script:
  - raco pkg setup

test:
  stage: test
  script:
    - raco test *.rkt

build:
  stage: build
  script:
    - raco exe main.rkt
